# == INSTRUCTIONS FOR SETTING UP TRAVIS ==
#
# 1. Find this repository in your Travis-CI dashboard.
#    open settings and add an environment variable called
#    GITHUB_ACCESS_TOKEN and set it to your personal access token.addons:
#    See: https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line
#
#    **DO NOT TURN ON 'Display value in build log'!!!!**
#
# 2. Push the code to the repository.

language: node_js
node_js:
  - lts/*

os: linux

addons:
  apt:
    packages:
      - libgconf-2-4 # cypress binary dependency

cache: npm

branches:
  only:
    - master

install:
  - npm ci

before_script:
  - npm run build # use nuxt build and start to run tests

script:
  - npm test

notifications:
  webhooks: https://www.travisbuddy.com
