version: "3.7"

services:
  web:
    build:
      context: .
    volumes:
      - "./.postwoman:/app/.postwoman"
      - "./assets:/app/assets"
      - "./directives:/app/directives"
      - "./layouts:/app/layouts"
      - "./middleware:/app/middleware"
      - "./pages:/app/pages"
      - "./plugins:/app/plugins"
      - "./static:/app/static"
      - "./store:/app/store"
      - "./components:/app/components"
    ports:
      - "3000:3000"
    command: "npm run dev"
